### ISSUE TITLE
Could we drop the use of `f` strings?

### ISSUE THREAD

**Issue by kevinhowbrook** [kaedroho/wagtail-localize#9]
From the classifiers [here](https://github.com/kaedroho/wagtail-localize/blob/master/setup.py#L32) it looks like we want to support previous python versions. I'm using 3.5.
Might not be worth it?

**Comment by kaedroho** [comment]
Yep, let's strip them out for now. Need to get Travis set up so this can be checked going forward

**Comment by kaedroho** [comment]
Fixed in #10
